지도학습 (X: 원인, Y: 결과 둘 다 입력!) - 문제와 답을 알려주고 새로운 문제에 대해 답을 내고자 함  
    예측: 새로운 X값들에 대해 Y값이 어떻게 될 것인지를 예측  
    분류: Y값이 어떤 그룹에 속할지를 분류  
        결과 그룹이 두개 - 이항 분류(생존:1, 사망:0)  
            학습할 때는 결과값을 0이나 1로 학습하지만, 머신러닝이나 딥러닝을 통해 도출한 결과값은  
            0 ~ 1 사이의 값이 출력되도록 하여 임계값 이상이면 1, 이하면 0이 출력되도록 함
        결과 그룹이 여러개 - 다항 분류  


    우리가 어떤 문제를 머신러닝/딥러닝을 통해 해결해야 한다면, 우선 예측인지 분류인지부터 생각해보자 
        (사실 대부분은 분류의 문제)  

비지도학습 (X: 원인 만 입력!)  
    클러스터링  
    생성  
    (예측, 분류도 포함)  

머신러닝 - 약속되어있는 통계적 수학 공식을 사용하여 오차를 계산하고 그 오차가 최소화되는
    최소제곱법에 의해서 w, b 결과를 찾아낸다  

딥러닝 - 무작위로 w, b를 만들어서 최소한의 공식만을 제공하여 계산하는데, 그 오차가 최소화되도록
    경사하강을 반복하며 w, b 결과를 찾아낸다  

In [31]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [32]:
#### 데이터 준비

x = np.array([1,2,1,1,1,2,2,1,1])       
y = np.array([100,200,100,50,10,20,20,10,10])
len(x),len(y),x.mean(), y.mean()

(9, 9, 1.3333333333333333, 57.77777777777778)

In [33]:
model = LinearRegression()  # 추정기 활성화
model.fit(np.reshape(x, (-1, 1)), y)    # w, b가 생성됨
w, b = model.coef_, model.intercept_

In [34]:
newX = 3
newX = np.reshape(newX, (-1, 1))
newY = newX*w + b
newY, model.predict(newX)

(array([[113.33333333]]), array([113.33333333]))

훈련 데이터 -> w, b값의 조절에 관여하는 데이터  
검증 데이터 -> 조절된 w, b값이 잘 되어있는지 확인하기 위한 데이터 -> 테스트 데이터로 사용되기도 함  

고전적인 머신러닝은 이미 공식이 만들어져있으므로, 검증이 불필요!  
    이미 만들어진 공식을 변경할 수 없으므로 훈련데이터를 이용해서 w, b만 fit 후 계산  
    이 w, b 값이 좋은 값인지를 테스트 데이터로 확인한다(오차가 작은지, 일치 확률이 어떤지) - 모델 검증  
    => 결과값이 좋으면 이 모델을 확정해서 새로운 데이터를 연동해본다  

딥러닝은 무작위로 w, b를 설정하고 훈련에 넣어 오차를 계산하고, 그 오차를 0으로 만들기 위해서  
경사 하강(오차 역전파)를 실시하여 훈련데이터는 무조건 오차가 줄어든다.  
    그러면 이 w, b 값이 좋은 값인지 확인하기 위해서, 검증 데이터를 그때 그때 넣어서 오차를 확인한다!  
    => 좋은 케이스: 훈련 데이터의 오차도 줄어들고, 검증 데이터의 오차도 줄어드는 경우! -> 계속 돌려도 된다  
    => 중단해야하는 경우(과적합): 훈련 데이터의 오차는 줄어드는데, 검증 데이터의 오차는 커지는 지점  

최종 작업이 다 끝나면 생성된 w, b가 들어있는 모델에 테스트 데이터를 넣어서 모델을 검증  
=> 결과값이 좋으면 이 모델을 확정해서 새로운 데이터를 연동해본다  

중요사항!  
    훈련 데이터는 fit하지만, 테스트 데이터는 fit하지 않는다

https://wikidocs.net/42596

In [35]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import make_column_transformer
from sklearn.linear_model import LogisticRegression
import numpy as np

In [36]:
train_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/binary_classification/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx?raw=true', sheet_name='train')
test_df = pd.read_excel('https://github.com/cranberryai/todak_todak_python/blob/master/machine_learning/binary_classification/%E1%84%90%E1%85%A1%E1%84%8B%E1%85%B5%E1%84%90%E1%85%A1%E1%84%82%E1%85%B5%E1%86%A8_b0fdSDZ.xlsx?raw=true', sheet_name='test')

In [37]:
labels = ['사망', '생존']
train_df.head()

pclass                            name     sex  age  sibsp  parch   ticket  \
0       2           Lehmann, Miss. Bertha  Female   17      0      0  SC 1748   
1       3  Laitinen, Miss. Kristina Sofia  Female   37      0      0     4135   
2       3     Rosblom, Mr. Viktor Richard    Male   18      1      1   370129   
3       3               Karaic, Mr. Milan    Male   30      0      0   349246   
4       3         Moen, Mr. Sigurd Hansen    Male   25      0      0   348123   

    fare embarked  survival  
0  12.00        C         1  
1   9.59        S         0  
2  20.21        S         0  
3   7.90        S         0  
4   7.65        S         0

In [38]:
##########데이터 분석 => 어떤 값들이 필요하고 필요하지 않은가를 분석

##########데이터 전처리 => 필요없을 것으로 생각된 변수들 + y값으로 사용할 변수를 제거

x_train = train_df.drop(['name', 'ticket', 'survival'], axis=1)
x_test = test_df.drop(['name', 'ticket', 'survival'], axis=1)
y_train = train_df['survival']
y_test = test_df['survival']

In [39]:
x_train.head()

# 머신러닝에 사용되는 데이터는 문자 데이터 없이 벡터 데이터만 있어야 하므로 sex, embarked 컬럼의 수정 필요
# sex 컬럼에서 Male = 0, Female = 1로 변경
# embarked를 0~3으로 변경할 경우, 이 값들의 크기가 의미를 가지는지 고민해보아야 한다.
# 값들의 크기에 의미가 없고, 학습에 영향을 줄 가능성이 있다면 더미변수화/원핫인코딩 필요 -> 0과 1의 벡터값으로 바꾼다

pclass     sex  age  sibsp  parch   fare embarked
0       2  Female   17      0      0  12.00        C
1       3  Female   37      0      0   9.59        S
2       3    Male   18      1      1  20.21        S
3       3    Male   30      0      0   7.90        S
4       3    Male   25      0      0   7.65        S

In [40]:
transformer = make_column_transformer(
    (OneHotEncoder(), ['pclass', 'sex', 'embarked']),
    remainder='passthrough')
transformer.fit(x_train)
x_train = transformer.transform(x_train)
x_test = transformer.transform(x_test)

In [41]:
x_train

array([[ 0.  ,  1.  ,  0.  , ...,  0.  ,  0.  , 12.  ],
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  9.59],
       [ 0.  ,  0.  ,  1.  , ...,  1.  ,  1.  , 20.21],
       ...,
       [ 0.  ,  0.  ,  1.  , ...,  0.  ,  0.  ,  8.66],
       [ 1.  ,  0.  ,  0.  , ...,  1.  ,  1.  , 52.55],
       [ 0.  ,  1.  ,  0.  , ...,  1.  ,  0.  , 26.  ]])

In [42]:
##########모델 생성

model = LogisticRegression()

##########모델 학습

model.fit(x_train, y_train)

##########모델 검증

print(model.score(x_train, y_train)) #0.7945205479452054

print(model.score(x_test, y_test)) #0.7795527156549521

0.7945205479452054
0.7763578274760383


c:\Users\bluecom015\miniconda3\envs\mp\lib\site-packages\sklearn\linear_model\_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


In [48]:
model.predict(x_test)[:5]

array([1, 0, 0, 0, 1], dtype=int64)

In [49]:
model.predict_proba(x_test)[:5]

array([[0.13255893, 0.86744107],
       [0.90263844, 0.09736156],
       [0.60909944, 0.39090056],
       [0.82349029, 0.17650971],
       [0.36005814, 0.63994186]])

In [44]:
##########모델 예측 - 새로운 값을 넣어서 테스트

newx_test = [
    [2, 'Female', 21, 0, 1, 21.00, 'S']
    ]
newx_test = pd.DataFrame(newx_test, columns=['pclass', 'sex', 'age', 'sibsp', 'parch', 'fare', 'embarked'])
newx_test = transformer.transform(newx_test)

In [45]:
y_predict = model.predict(newx_test)
label = labels[y_predict[0]]
y_predict = model.predict_proba(newx_test)
confidence = y_predict[0][y_predict[0].argmax()]

print(label, confidence) #

생존 0.8674410714255265
