In [2]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

x=np.array([1,2,3,4,5,6])
y=np.array([10,98,8,2,3,4])

In [3]:
input_layer = tf.keras.layers.InputLayer(input_shape=(1,))
hidden_layer1 = tf.keras.layers.Dense(units=4, activation='relu')
hidden_layer2 = tf.keras.layers.Dense(units=2, activation='relu')
output_layer= tf.keras.layers.Dense(units=1)

In [4]:
model = keras.Sequential([
    input_layer,
    hidden_layer1,
    hidden_layer2,
    output_layer
    ])

model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])
print(model.fit(x, y))
print(model.predict(x))
print(model.evaluate(x,y))

1/1 [==============================] - 0s 65ms/step
[[0.00099999]
 [0.00099999]
 [0.00099999]
 [0.00099999]
 [0.00099999]
 [0.00099999]]
1/1 [==============================] - 0s 97ms/step - loss: 1632.7916 - accuracy: 0.0000e+00
[1632.7916259765625, 0.0]


In [5]:
model_value = model.weights
model_value

[<tf.Variable 'dense/kernel:0' shape=(1, 4) dtype=float32, numpy=
 array([[-0.4718464 , -0.14578104, -0.6211628 ,  0.6930119 ]],
       dtype=float32)>,
 <tf.Variable 'dense/bias:0' shape=(4,) dtype=float32, numpy=array([0., 0., 0., 0.], dtype=float32)>,
 <tf.Variable 'dense_1/kernel:0' shape=(4, 2) dtype=float32, numpy=
 array([[ 0.34390187, -0.7704785 ],
        [-0.14731908,  0.9953518 ],
        [ 0.93335485,  0.7871423 ],
        [-0.6091571 , -0.05031466]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(2,) dtype=float32, numpy=array([0., 0.], dtype=float32)>,
 <tf.Variable 'dense_2/kernel:0' shape=(2, 1) dtype=float32, numpy=
 array([[0.51168334],
        [0.34579194]], dtype=float32)>,
 <tf.Variable 'dense_2/bias:0' shape=(1,) dtype=float32, numpy=array([0.00099999], dtype=float32)>]

In [6]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 4)                 8         
                                                                 
 dense_1 (Dense)             (None, 2)                 10        
                                                                 
 dense_2 (Dense)             (None, 1)                 3         
                                                                 
Total params: 21
Trainable params: 21
Non-trainable params: 0
_________________________________________________________________


In [7]:
intermediate_layer_model = tf.keras.Model(inputs=model.input, outputs=model.layers[0].output)
intermediate_output = intermediate_layer_model(x)

intermediate_output

<tf.Tensor: shape=(6, 4), dtype=float32, numpy=
array([[0.       , 0.       , 0.       , 0.6930119],
       [0.       , 0.       , 0.       , 1.3860238],
       [0.       , 0.       , 0.       , 2.0790358],
       [0.       , 0.       , 0.       , 2.7720475],
       [0.       , 0.       , 0.       , 3.4650593],
       [0.       , 0.       , 0.       , 4.1580715]], dtype=float32)>